batch_size: 128
epochs: 20
lr: 0.001

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: /content/extracted_data

# Preprocessing parameters
new_fs: 128
lowcut: 0.5
highcut: 40
baseline_correct: True

# Evaluation
model_path: /content/drive/My Drive/Colab Notebooks/DLBasics2023_colab/最終課題/MEG/dl_lecture_competition_pub/saved_model.pth
